(function(){
let gastoCats=["Alimentação","Transporte","Casa","Compras","Saúde","Lazer","Educação","Assinaturas","Contas","Outros"],entradaCats=["Salário","Vendas","Freelance","Investimentos","Reembolso","Outros"];
let dados=[],limite=0,hm="",initialized=false,authMode="login";
function $(id){return document.getElementById(id)}
function hoje(){let d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)}
function moeda(n){return Number(n||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}
function esc(s){return String(s==null?"":s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function aviso(t){let x=$("toast");x.textContent=t;x.className="toast show";clearTimeout(window.tm);window.tm=setTimeout(()=>x.className="toast",1900)}
function opts(el,a,first){el.innerHTML=(first?'<option value="">'+first+"</option>":"")+a.map(c=>"<option>"+esc(c)+"</option>").join("")}
function normalize(t){return {id:t.id,tipo:t.type==="income"?"entrada":"gasto",data:t.date,valor:Number(t.amount),categoria:t.category||"Outros",pagamento:t.payment_method==="credit_card"?"Cartão de crédito":"PIX",parcelas:Number(t.installments||1),obs:t.note||""}}
function toDb(x){return {type:x.tipo==="entrada"?"income":"expense",description:x.obs||x.categoria,amount:Number(x.valor),date:x.data,category:x.categoria,payment_method:x.tipo==="entrada"?"pix":(x.pagamento==="Cartão de crédito"?"credit_card":"pix"),installments:x.tipo==="entrada"?1:Number(x.parcelas||1),note:x.obs||""}}
function monthOf(s){return s.slice(0,7)}
function addMonths(date,n){let d=new Date(date+"T12:00:00");d.setMonth(d.getMonth()+n);return d.toISOString().slice(0,10)}
function occ(x,mes){if(x.tipo==="entrada")return monthOf(x.data)===mes?[{base:x,valor:x.valor,data:x.data,parcela:1,total:1}]:[];let n=Math.max(1,Math.min(6,x.parcelas||1)),r=[];for(let i=0;i<n;i++){let dt=addMonths(x.data,i);if(monthOf(dt)===mes)r.push({base:x,valor:Number((x.valor/n).toFixed(2)),data:dt,parcela:i+1,total:n})}if(r.length&&r[r.length-1].parcela===n&&n>1){let s=0;for(let j=0;j<n-1;j++)s+=Number((x.valor/n).toFixed(2));r[r.length-1].valor=Number((x.valor-s).toFixed(2))}return r}
function filtro(){let m=$("fMes").value,t=$("fTipo").value,c=$("fCat").value,r=[];dados.forEach(x=>{if(m)occ(x,m).forEach(o=>{if((!t||x.tipo===t)&&(!c||x.categoria===c))r.push(o)});else if((!t||x.tipo===t)&&(!c||x.categoria===c))r.push({base:x,valor:x.tipo==="gasto"?x.valor/x.parcelas:x.valor,data:x.data,parcela:1,total:x.parcelas})});return r.sort((a,b)=>b.data.localeCompare(a.data)||String(b.base.id).localeCompare(String(a.base.id)))}
function linha(o,acoes){let x=o.base,s=x.tipo==="entrada"?"+":"−",cl=x.tipo==="entrada"?"income":"expense",pc=x.tipo==="gasto"&&x.parcelas>1?" · Parcela "+o.parcela+"/"+o.total:"";return '<div class="item"><div><div class="desc">'+esc(x.obs||x.categoria)+' <span class="badge">'+esc(x.categoria)+'</span></div><div class="meta">'+(x.tipo==="entrada"?"Entrada":"Gasto")+(x.tipo==="gasto"?" · "+esc(x.pagamento)+pc:"")+' · '+new Date(o.data+"T12:00:00").toLocaleDateString("pt-BR")+'</div></div><div><div class="amount '+cl+'">'+s+" "+moeda(o.valor)+'</div>'+(acoes?'<button class="secondary mini" onclick="editar(\''+x.id+'\')">Editar</button><button class="danger mini" onclick="excluir(\''+x.id+'\')">Excluir</button>':"")+'</div></div>'}
function contaMes(m){let ent=0,pix=0,card=0;dados.forEach(x=>{if(x.tipo==="entrada"){if(monthOf(x.data)===m)ent+=x.valor}else occ(x,m).forEach(o=>{if(x.pagamento==="PIX")pix+=o.valor;else card+=o.valor})});return{ent,pix,card}}
function renderLimit(cardUsage){let pct=limite>0?cardUsage/limite*100:0;$("usoCartao").textContent=moeda(cardUsage);$("limiteTotal").textContent="Limite: "+moeda(limite);$("limiteDisp").textContent=moeda(limite-cardUsage);$("limitePct").textContent=(limite?Math.round(pct):0)+"%";$("bar").style.width=Math.min(100,Math.max(0,pct))+"%";$("bar").className="progressbar"+(pct>=100?" over":pct>=75?" warn":"");$("barText").textContent=(limite?Math.round(pct):0)+"% utilizado"+(pct>100?" · limite excedido":"")}
function render(){let m=$("fMes").value||hm,c=contaMes(m);$("saldo").textContent=moeda(c.ent-c.pix);$("entradas").textContent=moeda(c.ent);$("saidasPix").textContent=moeda(c.pix);$("cartaoMes").textContent=moeda(c.card);$("periodLabel").textContent="Saldo da conta · "+new Date(m+"-01T12:00:00").toLocaleDateString("pt-BR",{month:"long",year:"numeric"});renderLimit(c.card);let a=filtro();$("recent").innerHTML=a.slice(0,6).map(o=>linha(o,false)).join("")||'<div class="empty">Nenhum lançamento ainda.</div>';$('all').innerHTML=a.map(o=>linha(o,true)).join("")||'<div class="empty">Nenhum lançamento encontrado.</div>';renderMonthly();drawChart()}
function renderMonthly(){let m=$("mMes").value||hm,a=[];dados.forEach(x=>{if(x.tipo==="gasto")occ(x,m).forEach(o=>a.push(o))});a.sort((x,y)=>x.data.localeCompare(y.data));let total=a.reduce((s,o)=>s+o.valor,0);$("monthly").innerHTML='<div style="font-size:21px;font-weight:800;margin:9px 0 11px">'+moeda(total)+'</div>'+(a.map(o=>linha(o,false)).join("")||'<div class="empty">Nenhum gasto previsto neste mês.</div>')}
function drawChart(){let canvas=$("chart"),box=canvas.parentElement,w=box.clientWidth,h=box.clientHeight,dpr=window.devicePixelRatio||1;canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.width=w+"px";canvas.style.height=h+"px";let c=canvas.getContext("2d");c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,w,h);let m=$("gMes").value||hm,map={};dados.forEach(x=>{if(x.tipo==="gasto")occ(x,m).forEach(o=>map[x.categoria]=(map[x.categoria]||0)+o.valor)});let a=Object.keys(map).map(k=>[k,map[k]]).sort((x,y)=>y[1]-x[1]),tot=a.reduce((s,x)=>s+x[1],0),col=["#5d6c5c","#bfa75e","#7b8f7b","#cdaa7d","#87949a","#8e7b6a","#66705d","#9b7770","#59656a","#a39b84"];$("legend").innerHTML=a.map((x,i)=>'<div><span><i class="dot" style="background:'+col[i%col.length]+'"></i>'+esc(x[0])+'</span><b>'+moeda(x[1])+' · '+(tot?(x[1]/tot*100).toFixed(1):0)+'%</b></div>').join("")||'<div class="empty">Nenhum gasto neste mês.</div>';if(!a.length)return;let cx=w/2,cy=h/2,r=Math.min(w,h)*.33,ri=r*.58,s=-Math.PI/2;a.forEach((x,i)=>{let e=s+x[1]/tot*Math.PI*2;c.beginPath();c.arc(cx,cy,r,s,e);c.arc(cx,cy,ri,e,s,true);c.closePath();c.fillStyle=col[i%col.length];c.fill();s=e});c.fillStyle="#242929";c.textAlign="center";c.font="800 17px Arial";c.fillText(moeda(tot),cx,cy);c.font="12px Arial";c.fillStyle="#777";c.fillText("gastos",cx,cy+18)}
function updateForm(){let ent=document.querySelector('input[name="tipo"]:checked').value==="entrada";$("pagamentoArea").style.display=ent?"none":"block";opts($("fCategoria"),ent?entradaCats:gastoCats,"Escolha uma categoria")}
function openAuth(mode){authMode=mode;$("authTitle").textContent=mode==="login"?"Entrar":"Criar conta";$("authSubtitle").textContent=mode==="login"?"Acesse sua conta para continuar.":"Crie sua conta para começar.";$("authSubmit").textContent=mode==="login"?"Entrar":"Criar conta";$("authToggle").textContent=mode==="login"?"Criar uma conta":"Já tenho uma conta"}
async function startApp(){if(initialized)return;initialized=true;hm=hoje().slice(0,7);$("fData").value=hoje();$("fMes").value=hm;$("mMes").value=hm;$("gMes").value=hm;opts($("fCat"),gastoCats,"Todas as categorias");updateForm();prof=await getProfile();limite=Number(prof.credit_limit||0);$("limiteInput").value=limite||"";dados=(await getTransactions()).map(normalize);render()}
let prof=null;
window.onAuthChanged=async function(){if(currentUser){$("authScreen").style.display="none";$("appRoot").style.display="block";$("logout").style.display="";try{await startApp()}catch(e){console.error(e);aviso(e.message)}}else{$("authScreen").style.display="flex";$("appRoot").style.display="none";initialized=false}};
$("authForm").onsubmit=async e=>{e.preventDefault();let email=$("authEmail").value.trim(),pass=$("authPassword").value;$("authMessage").className="auth-message";$("authMessage").textContent="Processando...";let r=authMode==="login"?await doLogin(email,pass):await doSignup(email,pass);if(r.error){$("authMessage").className="auth-message error";$("authMessage").textContent=r.error.message}else{$("authMessage").className="auth-message success";$("authMessage").textContent=authMode==="login"?"Entrando...":"Conta criada. Se solicitado, confirme seu email."}};
$("authToggle").onclick=()=>openAuth(authMode==="login"?"signup":"login");
$("logout").onclick=async()=>{await doLogout();location.reload()};
$("saveLimit").onclick=async()=>{let v=Number(String($("limiteInput").value).replace(",","."));if(v<0||!Number.isFinite(v))return aviso("Digite um limite válido.");try{await setCreditLimit(v);limite=v;render();aviso("Limite atualizado.")}catch(e){aviso(e.message)}};
$("addForm").onsubmit=async e=>{e.preventDefault();let v=Number(String($("fValor").value).replace(",",".")),t=document.querySelector('input[name="tipo"]:checked').value;if(!v||v<=0)return aviso("Digite um valor válido.");let x={tipo:t,data:$("fData").value,valor:v,categoria:$("fCategoria").value,pagamento:t==="entrada"?"Entrada":document.querySelector('input[name="pag"]:checked').value,parcelas:t==="gasto"&&$("pCard").checked?Number($("fParcelas").value):1,obs:$("fObs").value.trim()};try{await insertTransaction(toDb(x));dados=(await getTransactions()).map(normalize);e.target.reset();$("fData").value=hoje();$("tGasto").checked=true;$("pPix").checked=true;$("fParcelas").value="1";$("parcelasArea").style.display="none";updateForm();render();aviso("Lançamento adicionado!")}catch(err){aviso(err.message)}};
window.excluir=async id=>{if(!confirm("Excluir este lançamento?"))return;try{await deleteTransaction(id);dados=(await getTransactions()).map(normalize);render();aviso("Lançamento excluído.")}catch(e){aviso(e.message)}};
window.editar=id=>{let x=dados.find(v=>String(v.id)===String(id));if(!x)return;$("eId").value=x.id;$("eTipo").value=x.tipo;$("eData").value=x.data;$("eValor").value=x.valor;$("eObs").value=x.obs||"";opts($("eCat"),x.tipo==="entrada"?entradaCats:gastoCats);$("eCat").value=x.categoria;$("ePag").value=x.pagamento==="Cartão de crédito"?"Cartão de crédito":"PIX";$("eParcelas").value=String(x.parcelas||1);$("editPayBox").style.display=x.tipo==="entrada"?"none":"block";$("modal").className="modal show"};
$("eTipo").onchange=()=>{let en=$("eTipo").value==="entrada";opts($("eCat"),en?entradaCats:gastoCats);$("editPayBox").style.display=en?"none":"block"};$("close").onclick=()=>$("modal").className="modal";
$("editForm").onsubmit=async e=>{e.preventDefault();let id=$("eId").value,x=dados.find(v=>String(v.id)===String(id));if(!x)return;x.tipo=$("eTipo").value;x.data=$("eData").value;x.valor=Number($("eValor").value);x.categoria=$("eCat").value;x.obs=$("eObs").value.trim();x.pagamento=x.tipo==="entrada"?"Entrada":$("ePag").value;x.parcelas=x.tipo==="entrada"?1:Number($("eParcelas").value);try{await updateTransaction(id,toDb(x));dados=(await getTransactions()).map(normalize);$("modal").className="modal";render();aviso("Alterações salvas.")}catch(err){aviso(err.message)}};
$("fMes").onchange=render;$("fTipo").onchange=render;$("fCat").onchange=render;$("mMes").onchange=renderMonthly;$("gMes").onchange=drawChart;window.addEventListener("resize",drawChart);
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.tab).classList.add("active");if(b.dataset.tab==="graficos")setTimeout(drawChart,20)});
$("new").onclick=()=>{document.querySelector('[data-tab="resumo"]').click();window.scrollTo({top:0,behavior:"smooth"});setTimeout(()=>$("fValor").focus(),250)};
$("erase").onclick=async()=>{if(!confirm("Apagar TODOS os lançamentos da sua conta? Esta ação não pode ser desfeita."))return;try{await deleteAllTransactions();dados=[];render();aviso("Todos os lançamentos foram apagados.")}catch(e){aviso(e.message)}};
$("tGasto").onchange=updateForm;$("tEntrada").onchange=updateForm;$("pCard").onchange=()=>$("parcelasArea").style.display="block";$("pPix").onchange=()=>{$("parcelasArea").style.display="none";$("fParcelas").value="1"};
initAuth().then(()=>window.onAuthChanged()).catch(e=>{$("authMessage").className="auth-message error";$('authMessage').textContent=e.message});openAuth("login");
})();
