let d=new Date(),all=[],prof=null,mode='login';const $=x=>document.getElementById(x),br=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v||0);
function mkey(){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function renderAuth(){if(!window.SUPABASE_URL||window.SUPABASE_URL.includes('COLE_AQUI')){$('authMsg').textContent='Abra js/config.js e coloque os dados do Supabase.';return}
if(user){$('auth').classList.add('hidden');$('app').classList.remove('hidden');$('logout').classList.remove('hidden');$('fab').classList.remove('hidden');init()}else{$('auth').classList.remove('hidden');$('app').classList.add('hidden');$('logout').classList.add('hidden');$('fab').classList.add('hidden')}}
async function init(){try{prof=await profile();all=await transactions();render()}catch(e){alert(e.message)}}
function render(){ $('month').textContent=new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(d);let c=calc(all,mkey());$('balance').textContent=br(c.balance);$('income').textContent=br(c.income);$('pix').textContent=br(c.pix);$('card').textContent=br(c.card);$('used').textContent=br(c.card);$('future').textContent=br(future(all,mkey()));let lim=+prof.credit_limit||0;$('limit').textContent='Limite: '+br(lim);$('bar').style.width=(lim?Math.min(100,c.card/lim*100):0)+'%';let l=$('list');l.innerHTML='';$('empty').classList.toggle('hidden',c.items.length>0);c.items.forEach(t=>{let x=document.createElement('div');x.className='tx';x.innerHTML=`<div class="ico">${t.type==='income'?'↑':t.payment_method==='credit_card'?'▣':'↓'}</div><div><b>${esc(t.description)}</b><small>${esc(t.category)} · ${t.type==='income'?'Entrada':t.payment_method==='credit_card'?`Cartão ${t.idx}/${t.n}`:'PIX'}</small></div><strong class="${t.type==='income'?'pos':'neg'}">${t.type==='income'?'+':'−'} ${br(t.displayAmount)}</strong>`;x.onclick=()=>openTx(t);l.appendChild(x)})}
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function openTx(t=null,type='expense'){$('txModal').classList.remove('hidden');$('editId').value=t?.id||'';$('type').value=t?.type||type;$('txTitle').textContent=t?'Editar lançamento':type==='income'?'Nova entrada':'Nova saída';$('desc').value=t?.description||'';$('amount').value=t?.amount||'';$('date').value=t?.date||new Date().toISOString().slice(0,10);$('category').value=t?.category||'Outros';$('payment').value=t?.payment_method||'pix';$('inst').value=t?.installments||1;$('note').value=t?.note||'';$('del').classList.toggle('hidden',!t);ui()}
function ui(){$('payment').disabled=$('type').value==='income';$('instWrap').classList.toggle('hidden',$('type').value==='income'||$('payment').value!=='credit_card')}
$('authForm').onsubmit=async e=>{e.preventDefault();let r=mode==='login'?await login($('email').value,$('password').value):await signup($('email').value,$('password').value);$('authMsg').textContent=r.error?r.error.message:mode==='login'?'Entrando...':'Conta criada. Confirme o email se solicitado.'}
$('toggle').onclick=()=>{mode=mode==='login'?'signup':'login';$('authTitle').textContent=mode==='login'?'Entrar':'Criar conta';$('authSub').textContent=mode==='login'?'Acesse sua conta.':'Crie sua conta para começar.';$('authForm').querySelector('button').textContent=mode==='login'?'Entrar':'Criar conta';$('toggle').textContent=mode==='login'?'Criar uma conta':'Já tenho uma conta'}
$('logout').onclick=async()=>{await logout();location.reload()};$('prev').onclick=()=>{d.setMonth(d.getMonth()-1);render()};$('next').onclick=()=>{d.setMonth(d.getMonth()+1);render()};$('fab').onclick=()=>openTx(null,'expense');document.querySelectorAll('.actions button').forEach(b=>b.onclick=()=>openTx(null,b.dataset.type));$('payment').onchange=ui;
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).classList.add('hidden'));
$('cardSettings').onclick=()=>{$('setModal').classList.remove('hidden');$('creditLimit').value=prof.credit_limit||0};
$('setForm').onsubmit=async e=>{e.preventDefault();await saveLimit($('creditLimit').value);prof=await profile();$('setModal').classList.add('hidden');render()};
$('txForm').onsubmit=async e=>{e.preventDefault();let t={type:$('type').value,description:$('desc').value.trim(),amount:+$('amount').value,date:$('date').value,category:$('category').value,payment_method:$('payment').value,installments:$('payment').value==='credit_card'?+$('inst').value:1,note:$('note').value.trim()};try{await saveTx(t,$('editId').value||null);all=await transactions();$('txModal').classList.add('hidden');render()}catch(x){$('txMsg').textContent=x.message}};
$('del').onclick=async()=>{if(confirm('Excluir este lançamento?')){await removeTx($('editId').value);all=await transactions();$('txModal').classList.add('hidden');render()}};
session().then(renderAuth).catch(e=>$('authMsg').textContent=e.message);
